version: '3.1'
services:
  sample-api:
    image: mouselightdatabrowser/sample-api:1.7
    hostname: sample-api
    environment:
      NODE_ENV: production
      DATABASE_PW:
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9671:5000
    networks:
      - back_tier

  sample-client:
    image: mouselightdatabrowser/sample-client:1.7
    hostname: sample-client
    environment:
      NODE_ENV: production
      SAMPLE_AUTH_PASS: "${AUTH_PASS_TEAM}"
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9673:5000
    networks:
      - back_tier

  swc-api:
    image: mouselightdatabrowser/swc-api:1.4
    hostname: swc-api
    environment:
      NODE_ENV: production
      DATABASE_PW:
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9651:5000
    networks:
      - back_tier

  swc-client:
    image: mouselightdatabrowser/swc-client:1.4
    hostname: swc-client
    environment:
      NODE_ENV: production
      SWC_AUTH_PASS: "${AUTH_PASS_TEAM}"
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9653:5000
    networks:
      - back_tier

  transform-api:
    image: mouselightdatabrowser/transform-api:1.6
    hostname: transform-api
    environment:
      NODE_ENV: production
      DATABASE_PW:
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
      - "${TRANSFORM_VOL_EXT}:${TRANSFORM_VOL_INT}"
    ports:
      - 9661:5000
    networks:
      - back_tier

  transform-client:
    image: mouselightdatabrowser/transform-client:1.6
    hostname: transform-client
    environment:
      NODE_ENV: production
      TRANSFORM_AUTH_PASS: "${AUTH_PASS_TEAM}"
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9663:5000
    networks:
      - back_tier

  transform-search:
    image: mouselightdatabrowser/transform-search:1.4
    hostname: transform-search
    environment:
      NODE_ENV: production
      TRANSFORM_API_PORT: 5000
      TRANSFORM_AUTH_PASS: "${AUTH_PASS_TEAM}"
    ports:
      - 9665:9665
    networks:
      - back_tier

  search-api:
    image: mouselightdatabrowser/search-api:1.7
    hostname: search-api
    environment:
      NODE_ENV: production
      SEARCH_API_RELEASE_LEVEL: "Internal"
      DATABASE_PW:
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9681:5000
    networks:
      - back_tier

  search-internal-client:
    image: mouselightdatabrowser/search-client:1.7
    hostname: search-internal-client
    environment:
      NODE_ENV: production
      SEARCH_API_HOST: search-api
      SEARCH_AUTH_PASS: "${AUTH_PASS_INTERNAL}"
      SEARCH_CLIENT_SCOPE: "Internal"
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9683:5000
    networks:
      - back_tier
    links:
      - search-api

  search-team-client:
    image: mouselightdatabrowser/search-client:1.7
    hostname: search-team-client
    environment:
      NODE_ENV: production
      SEARCH_API_HOST: search-api
      SEARCH_AUTH_PASS: "${AUTH_PASS_TEAM}"
      SEARCH_CLIENT_SCOPE: "Team"
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9685:5000
    networks:
      - back_tier
    links:
      - search-api

  static-api:
    image: mouselightdatabrowser/static-resources:1.7
    hostname: static-api
    environment:
      NODE_ENV: production
      STATIC_API_IS_INTERNAL: 1
      STATIC_SLICE_MOUNT_POINT: "/data/slice/"
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
      - "${MNB_SLICE_LOCATION}:/data/slice"
    ports:
      - 9691:5000
    networks:
      - back_tier

  export-api:
    image: mouselightdatabrowser/export-api:1.7
    hostname: export-api
    environment:
      NODE_ENV: production
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
      - "${EXPORT_DATA_LOCATION}:/opt/data/export"
    ports:
      - 9693:5000
    networks:
      - back_tier

  internal-proxy:
    build:
      context: nginx-internal
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      API_KEY: "${AMPLIFY_API_KEY}"
      AMPLIFY_IMAGENAME:
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9664:80
    networks:
      - back_tier
    links:
      - static-api
      - export-api
      - search-api
      - search-internal-client

  team-proxy:
    build:
      context: nginx-team
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - "${MNB_LOG_VOLUME}:/var/log/mnb"
    ports:
      - 9666:80
    networks:
      - back_tier
    links:
      - static-api
      - export-api
      - search-api
      - search-team-client

volumes:
  log_output:

networks:
  back_tier:
