version: '3.1'
services:
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "9664:80"
    networks:
      - back_tier

  metrics-db:
    image: influxdb
    hostname: metrics-db
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - influx_config:/etc/influxdb
    networks:
      - back_tier

  grafana:
    image: grafana/grafana
    hostname: grafana-metrics
    ports:
      - 8087:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_NAME: "Janelia"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
      - grafana_log:/var/log/grafana
    networks:
      - back_tier

  sample-db:
    image: postgres:9
    container_name: "ndb_sample_db"
    hostname: sample-db
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - sample_data:/var/lib/postgresql/data
      - ./datastore/sample:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  swc-db:
    image: postgres:9
    container_name: "ndb_swc_db"
    hostname: swc-db
    ports:
      - 5433:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - swc_data:/var/lib/postgresql/data
      - ./datastore/swc:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  transform-db:
    image: postgres:9
    container_name: "ndb_transform_db"
    hostname: transform-db
    ports:
      - 5434:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - transform_data:/var/lib/postgresql/data
      - ./datastore/transform:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  search-db:
    image: postgres:9
    container_name: "ndb_search_db"
    hostname: search-db
    ports:
      - 5435:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - search_data:/var/lib/postgresql/data
      - ./datastore/search:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  data:
    image: mouselightdatabrowser/data
    container_name: "ndb_data"
    hostname: ndb-data
    environment:
      NODE_ENV: production
    volumes:
      - "${DATA_VOL}:/opt/data"
    networks:
      - back_tier

  sample-api:
    image: mouselightdatabrowser/sample-api
    container_name: "ndb_sample_api"
    hostname: sample-api
    environment:
      NODE_ENV: production
    ports:
      - 9671:9671
    networks:
      - back_tier

  sample-web:
    image: mouselightdatabrowser/sample-client
    container_name: "ndb_sample_client"
    hostname: sample-client
    environment:
      NODE_ENV: production
      SAMPLE_SERVICE_PORT: 9671
    ports:
      - 9673:9673
    networks:
      - back_tier

  swc-api:
    image: mouselightdatabrowser/swc-api
    container_name: "ndb_swc_api"
    hostname: swc-api
    environment:
      NODE_ENV: production
    ports:
      - 9651:9651
    networks:
      - back_tier

  swc-web:
    image: mouselightdatabrowser/swc-client
    container_name: "ndb_swc_client"
    hostname: swc-client
    environment:
      NODE_ENV: production
      SWC_SERVICE_PORT: 9651
      SAMPLE_SERVICE_PORT: 9641
    ports:
      - 9653:9653
    networks:
      - back_tier

  transform-api:
    image: mouselightdatabrowser/transform-api
    container_name: "ndb_transform_api"
    hostname: transform-api
    environment:
      NODE_ENV: production
      NEURON_EXPLORER_RELEASE: internal
    volumes:
      - "${DATA_VOL}:/opt/data"
      - "${TRANSFORM_VOL}:/groups/mousebrainmicro/mousebrainmicro"
    ports:
      - 9661:9661
    networks:
      - back_tier

  transform-client:
    image: mouselightdatabrowser/transform-client
    container_name: "ndb_transform_client"
    hostname: transform-client
    environment:
      NODE_ENV: production
    ports:
      - 9663:9663
    networks:
      - back_tier

  search-api-1:
    image: mouselightdatabrowser/search-api
    container_name: "ndb_search-api-1"
    hostname: search-api-1
    environment:
      NODE_ENV: production
      NEURON_EXPLORER_RELEASE: internal
    ports:
      - 9681:9681
    networks:
      - back_tier

  search-client-1:
     image: mouselightdatabrowser/search-client
     hostname: search-client-1
     environment:
       NODE_ENV: production
       TRANSFORM_API_HOST: search-api-1
     ports:
       - 9683:9683
     networks:
       - back_tier

  landing:
    image: mouselightdatabrowser/landing
    hostname: landing
    environment:
      NODE_ENV: production
    ports:
      - 80:9000
    networks:
      - back_tier

volumes:
  influx_data:
  influx_config:
  grafana_config:
  grafana_log:
  grafana_data:
  sample_data:
  swc_data:
  transform_data:
  search_data:

networks:
  back_tier:
