version: '3.1'
services:
  data-services:
    image: mouselightdatabrowser/data-services:1.4
    hostname: data-services
    environment:
      NODE_ENV: production
    volumes:
    - "${MNB_BACKUP_LOCATION}:/opt/data/backup"
    networks:
    - back_tier

  sample-api:
    image: mouselightdatabrowser/sample-api:1.4
    hostname: sample-api
    environment:
      NODE_ENV: production
      DATABASE_PW:
    ports:
    - 9671:5000
    networks:
    - back_tier

  sample-client:
    image: mouselightdatabrowser/sample-client:1.4
    hostname: sample-client
    environment:
      NODE_ENV: production
      SAMPLE_AUTH_PASS: "${AUTH_PASS_TEAM}"
    ports:
    - 9673:5000
    networks:
    - back_tier

  swc-api:
    image: mouselightdatabrowser/swc-api:1.4
    hostname: swc-api
    environment:
      NODE_ENV: production
      DATABASE_PW:
    ports:
    - 9651:5000
    networks:
    - back_tier

  swc-client:
    image: mouselightdatabrowser/swc-client
    hostname: swc-client
    environment:
      NODE_ENV: production
      SWC_SERVICE_PORT: 5000
      SWC_AUTH_PASS: "${AUTH_PASS_TEAM}"
    ports:
    - 9653:9653
    networks:
    - back_tier

  transform-api:
    image: mouselightdatabrowser/transform-api
    hostname: transform-api
    environment:
      NODE_ENV: production
      DATABASE_PW:
    volumes:
    - "${TRANSFORM_VOL_EXT}:${TRANSFORM_VOL_INT}"
    ports:
    - 9661:9661
    networks:
    - back_tier

  transform-client:
    image: mouselightdatabrowser/transform-client
    hostname: transform-client
    environment:
      NODE_ENV: production
      TRANSFORM_AUTH_PASS: "${AUTH_PASS_TEAM}"
    ports:
    - 9663:9663
    networks:
    - back_tier

  transform-search:
    image: mouselightdatabrowser/transform-search
    hostname: transform-search
    environment:
      NODE_ENV: production
      TRANSFORM_AUTH_PASS: "${AUTH_PASS_TEAM}"
    ports:
    - 9665:9665
    networks:
    - back_tier

  search-api:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-api
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: internal
      DATABASE_PW:
    ports:
    - 9681:9681
    networks:
    - back_tier

  search-client:
    image: mouselightdatabrowser/search-client:1.4
    hostname: search-client
    environment:
      NODE_ENV: production
      SEARCH_API_HOST: search-api
      SEARCH_AUTH_PASS: "${AUTH_PASS_INTERNAL}"
    ports:
    - 9683:9683
    networks:
    - back_tier
    links:
    - search-api

  search-team-api:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-team-api
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: team
      SEARCH_DB_HOST: search-team-db
      DATABASE_PW:
    ports:
    - 9685:9681
    networks:
    - back_tier

  search-team-client:
    image: mouselightdatabrowser/search-client:1.4
    hostname: search-team-client
    environment:
      NODE_ENV: production
      SEARCH_API_HOST: search-team-api
      SEARCH_AUTH_PASS: "${AUTH_PASS_TEAM}"
    networks:
    - back_tier
    ports:
    - 9687:9683
    links:
    - search-team-api

  export-api:
    image: mouselightdatabrowser/export-api:1.4
    hostname: export-api
    environment:
      NODE_ENV: production
    volumes:
    - "${EXPORT_DATA_LOCATION}:/opt/data/export"
    ports:
    - 9691:9691
    networks:
    - back_tier

  internal-proxy:
    build:
      context:  nginx-internal
      dockerfile: Dockerfile
    environment:
      API_KEY: "${AMPLIFY_API_KEY}"
      AMPLIFY_IMAGENAME: "${INTERNAL_AMPLIFY_IMAGENAME}"
    ports:
    - 9664:80
    networks:
    - back_tier
    links:
    - export-api
    - search-api
    - search-client

  team-proxy:
    build:
      context:  ./nginx-team
      dockerfile: Dockerfile
    environment:
      API_KEY: "${AMPLIFY_API_KEY}"
      AMPLIFY_IMAGENAME:  "${TEAM_AMPLIFY_IMAGENAME}"
    ports:
    - 9666:80
    networks:
    - back_tier
    links:
    - export-api
    - search-team-api
    - search-team-client
