version: '3.1'
services:
  message-queue:
    image: rabbitmq:3-management
    container_name: "ndb_message_queue"
    hostname: message-queue
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "mqsecret"
    volumes:
      - mq_data:/var/lib/rabbitmq
    networks:
      - back_tier

  sample-db:
    image: postgres:9
    container_name: "ndb_sample_db"
    hostname: sample-db
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - sample_data:/var/lib/postgresql/data
      - ./datastore/sample:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  swc-db:
    image: postgres:9
    container_name: "ndb_swc_db"
    hostname: swc-db
    ports:
      - 5433:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - swc_data:/var/lib/postgresql/data
      - ./datastore/swc:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  transform-db:
    image: postgres:9
    container_name: "ndb_transform_db"
    hostname: transform-db
    ports:
      - 5434:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - transform_data:/var/lib/postgresql/data
      - ./datastore/transform:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  transform-api:
    image: mouselightdatabrowser/transform-api
    container_name: "ndb_transform_api"
    hostname: transform-api
    environment:
      NODE_ENV: production
    volumes:
      - /opt/data:/opt/data
      - /mnt/groups:/mnt/groups
    ports:
      - 9661:9661
    networks:
      - back_tier

volumes:
  mq_data: 
  sample_data:
  swc_data:
  transform_data:

networks:
  back_tier:
